light_gbm: |
  {'n_estimators': numpy.arange(50,550,50),
  'boosting_type': ['gbdt', 'goss', 'dart'],
  'num_leaves': list(range(100, 150,3)),
  'learning_rate': list(numpy.logspace(numpy.log10(0.005), numpy.log10(0.5), base = 10, num = 500)),
  'subsample_for_bin': list(range(20000, 300000, 20000)),
  'min_child_samples': list(range(20, 500, 5)),
  'reg_alpha': list(numpy.linspace(0, 1)),
  'reg_lambda': list(numpy.linspace(0, 1)),
  'colsample_bytree': list(numpy.linspace(0.6, 1, 10)),
  'subsample': list(numpy.linspace(0.5, 1, 100)),
  'scale_pos_weight': [1, 1.3, 1.5]
  }